general.import = [
]

[window.dimensions]
columns = 130
lines = 40

[window]
padding.x = 10 
padding.y = 10 
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 23  
